message("Selecting unit-test backend ...")

if(TMP_ENABLE_CUDA_BACKEND)
    message("Building tests using ExecutionSpaceCUDA")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTMP_ENABLE_CUDA_BACKEND")
elseif(TMP_ENABLE_HIP_BACKEND)
    message("Building tests using ExecutionSpaceHIP")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTMP_ENABLE_HIP_BACKEND")
elseif(TMP_ENABLE_OPENMP_BACKEND)
    message("Building tests using ExecutionSpaceOpenMP")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTMP_ENABLE_OPENMP_BACKEND")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
else()
    message("Building tests using ExecutionSpaceSerial")
endif()